
name: docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'PyPtt/*.py'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'PyPtt/*.py'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[update-docs]')"
    steps:
    - uses: actions/setup-python@master
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        requirements_path: docs/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages